# Generated by Django 4.2.6 on 2023-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم')),
                ('info', models.CharField(max_length=100, verbose_name='توضیحات')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('time', models.IntegerField(verbose_name='زمان آماده شدن')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('photo', models.ImageField(upload_to='food_images/')),
                ('type_food', models.CharField(choices=[('drinks', 'نوشیدنی'), ('dinner', 'صبحانه'), ('lunch', 'غذای اصلی')], default='drink', max_length=10, verbose_name='نوع خوراکی')),
            ],
            options={
                'verbose_name': ' غذا',
                'verbose_name_plural': 'غذاها',
            },
        ),
    ]
