# Generated by Django 4.2.6 on 2023-10-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل ')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('date', models.DateField(verbose_name='تاریخ')),
                ('time', models.TimeField(verbose_name='زمان')),
                ('number', models.IntegerField(verbose_name='تعداد')),
            ],
            options={
                'verbose_name': ' رزرو ',
                'verbose_name_plural': ' رزرو شده ها ',
            },
        ),
    ]
